[[section-introduction-and-goals]]
== Introduction and Goals

This project is based on Solid

[role="arc42help"]
****
Describes the *relevant* requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

=== Requirements Overview
.What is Viade?
	It is a decentralized route management system based on the Solid specifications and developed using the React framework.
	
.Main requirements
	* Routes. Users can store their routes in their own pods and visualize them on a map.
	* Decentralized aschitecture. The system will be based on a decentralized architecture in which the data is separated from the application and stored in a user POD.
	* Files. The application allows you to share different types of files (photos, videos ...) with your friends and users 	will receive notifications from their friends to share a route.
	* Groups. You can create groups of friends with whom routes will be shared.
	* Interoperable. Viade is interoperable and allows viewing routes loaded by users using different applications.

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

[options="header",cols="1,2,7"]
|===
|Nr.|Quality|Motivations
| 1 | Privacy | The user data should be private and only them can share it, all the data should be stored in individual solid pods.
| 2 | Availability | The app and the user data should be available always
| 3 | Usability | The app should be simple to understand and to use. This app is meant for users with no technical knowledge
| 4 | Modularity | The app should be modular by using react components to build the app easily and efficiently
| 5 | Testability | The app should be able to be tested
|===

=== Stakeholders

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| End users | Refers to any user of the system. | Being able to use the system intuitively and without any problem
| Project developers | They are the developer team who'll carry out the design and implementation of the project | Creating a system that meets the requirements and quality goals initially established throughout the whole development, dealing with any kind of issue, being able to solve them and learning from them
| Subject teachers | They guide and evaluate the development team and provide them the required frameworks to carry out the project. In addition to resolving all doubts that come up in the development process | They expect developers to learn to use and familiarize with new development environmets and technologies which are possibly new for them, also learning to deal with teamwork
| SOLID Community | All contributors and people related to the SOLID Project | They expect that anyone interested in the SOLID project ask them for help when necessary, apart from learning more about decentralized technologies, and giving them more importance
|===
