[[section-architecture-constraints]]
== Architecture Constraints

=== Technical Constraints

PODs::
_Our project architecture will be decentralized, so that user data is separated from the application that uses it.
To this we are following Solid especifications. Solid is based on network technology that makes users owners of their 
own data, which they store using their own PODs._

React::
_We will develop ViaDe using React: a JavaScript library used to create user 
interactive interfaces which is based on encapsulated components which manage their own state and they 
are composed to create complex user interfaces.
React allows you to design simple views for each application 
state, and it will update and render efficiently
the correct components whenever their data changes_

=== Organizational Constraints

GitHub::
_It is a collaborative development platform to control versions in which we
have the repository and work on it._

Time::
_We are developing this application in a limited and reduced amount of Time
that it is defined by the duration of the subject Software Architecture, which
lasts about 3 months._

=== Documentation Constraints

Arc42::
_We are using the format Arc42 for the documentation of the ViaDe project. It provides 
a template for documentation and communication of software for lean and
agile development._

