[[section-solution-strategy]]
== Solution Strategy

Our application is based on the REACT framework and uses a SOLID architecture where data 
is stored in a decentralized way.
We'll use the software architecture pattern known as Flux, recomended for React applications.


In addition, we take advantage of being a group of 7 people to be able to divide the work and
being able to test everything we are doing, while the software is on development.
So while some ones are developing functional code, other ones can be testing the software. Or at least that's the plan.
The members of the group maintain contact by making calls by discord, which is an application
which allows free calls and screen sharing, in addition to weekly lab classes
in which we meet.
We must recognize that we have divided the work a bit randomly because we still do not know
the strengths and weaknesses of each member, since we do not know anything yet, but as
advance the project we will distribute the work better based on our skills, not random.