[[section-solution-strategy]]
== Solution Strategy

Our application is based on the REACT framework and uses a SOLID architecture where data 
is stored in a decentralized way.
We'll use the software architecture pattern known as Flux, recomended for React applications.

=== Back-end
We store the routes in the SOLID pod using the format https://json-ld.org/[JSON-LD] which is recommended as it's easy to manipulate with open source libraries like https://github.com/LDflex/LDflex[LDflex].

=== Front-end
We are using React js library to do the user interface and we are focusing on making a user friendly application.
We need to show the points in a map somehow, so we decided to use the https://www.npmjs.com/package/react-google-maps[google maps api] as we already have some api keys.
As long as the project is in development, we can keep using this api because is free.
If in the future there are hundreds of users viewing routes at the same time, we'll need to pay but now we don't need to worry about that.
