[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****
These are some representations of the ViaDe scenarios, that will be updated throughout the creation of the app.

=== Store information
It is a decentralized information storage system, in which users send the information to the app and save it in their respective POD


[plantuml,"Sequence diagram",png]
----
actor UserX
participant app
participant UserX_POD
UserX -> app: share route infomation (photos, videos and comments)
app -> UserX_POD: store information
----
=== Share information
To see the routes of your friends you will interact with the application and this will be the one that takes the information of your friends POD if you are allowed access to that information.
[plantuml,"Sequence diagram",png]
----
actor User1
participant app
actor User2
User1 -> app:store route 
app -> User2:share User1's route
User2 -> app:store route 
app -> User1:share User2's route
----
==
