[[section-concepts]]
== Cross-cutting Concepts

=== Domain

As explained in previous sections, there will be the following concepts related to the domain:

* User
* Friend (relationship)
* Route

Apart from the above, we could talk about the POD concept but we won't, we'll explain why later.

=== User Experience

The point of this application is to try to simplify the UX, therefore it's important to make the user forget about the existence of PODs in the mean of the possible in order to simplify the usage and familiarize more easily.
We want the application to have a UX that remembers to big social networks (i.e: Twitter, Facebook), because almost any potential user will know how to use it.

==== User interface

Facing the user interface, we want it to be very intuitive, in addition to maintaining a clean and simple aesthetic.

==== Ergonomics

To achieve a simple UI it's a must to minimize the features shown, letting the user to explore and get used to the main ones. It's not about overwhelming the user with many different features, menus and options.

=== Safety and security

Thanks to the use of POD the concept (https://solidproject.org/use-solid/#get-a-pod-and-a-webid[SOLID Project]), data will be secure and we won't have to worry about the that.

=== Architecture and design patterns

We'll use MVC architectural pattern (Model View Controller), digging into the model, the stored data will be handled by SOLID PODs as said before.

=== Under-the-hood

==== Persistence

We won't directly store users data, we will rely on SOLID PODs for that task, to accomplish one of the SOLID project goals, decentralize the data.