[[section-design-decisions]]
== Design Decisions

[cols="1,1,1,2,2",options="header"]
|===
|Date
|Decision
|Participants
|Pros
|Cons

|17/02/2020
|Usage of React over React Native
|Whole group
a|
* The teachers are more able to help us with React than with Native, as they have not worked with the 
latter.
* Plenty of documentation and tutorials online, including some about converting React code into React 
Native. 
a|
* If we decided in the future to allow the app to work in mobile devices, we will have to convert our 
code to React Native. If we had started already in Native, this adaptation would not be necessary.

|28/02/2020
|Usage of Google Maps API
|Whole group
a|
* Plenty of documentation, tutorials and examples of usage online, by far the most documented API related
to maps. 
* It has been used before by some group members, which makes it easier to have it working properly.
a|

|23/03/2020
|Usage of viadeSpec's JSON-LD standard
|Whole group
a|
* Plenty of documentation on how to manage JSON.
* It has been used before by every member of the group.
* Improves interoperability with the applications developed by other groups.
a|
* PODs do not support this format, so we will not be able to visualize the data as we would be able to if
we were to use Turtle, for example.

|04/04/2020
|Storage of groups using a JSON
|Álvaro Tango Fernández, Marcos Álvarez Vidal, Sergio Corral Cristo
a|
* Easiness of management, as we know how to properly manage a JSON file.
* Possibility of switching the information we want to save about the group in a very straight-forward way.
a|
* Not taking advantage of the PODs built-in address book system, which allows you to create groups of people.

|13/04/2020
|Adaptation to small screens (Mobile devices)
|Whole group
a|
* Allows the application to be compatible with mobile devices without the inconvenients of building it using
React native.
a|

|13/04/2020
|Usage of Enzyme to do unit testing
|Whole group
a|
* Better capability of asserting, manipulating and traversing the component's output.
a|

|===
