[[section-design-decisions]]
== Design Decisions

[cols="1,1,1,2,2",options="header"]
|===
|Date
|Decision
|Participants
|Pros
|Cons

|17/02/2020
|Usage of React over React Native
|Whole group
a|
* The teachers are more able to help us with React than with Native, as they have not worked with the 
latter.
* Plenty of documentation and tutorials online, including some about converting React code into React 
Native. 
a|
* If we decided in the future to allow the app to work in mobile devices, we will have to convert our 
code to React Native. If we had started already in Native, this adaptation would not be necessary.

|28/02/2020
|Usage of Google Maps API
|Whole group
a|
* Plenty of documentation, tutorials and examples of usage online, by far the most documented API related
to maps. 
* It has been used before by some group members, which makes it easier to have it working properly.
a|

|13/04/2020
|Adaptation to small screens (Mobile devices)
|Whole group
a|
* Allows the application to be compatible with mobile devices without the inconvenients of building it using
React native.
a|

|13/04/2020
|Usage of Enzyme to do unit testing
|Whole group
a|
* Better capability of asserting, manipulating and traversing the component's output.
a|

|20/04/2020
|Implementation of a COVID related utility
|Whole group
a|
* Due to the situation being so difficult right now, any sort of help we can provide is something to aim for, and
showcasing COVID-related data might prevent more people to be infected while doing a route.
a|

|===
