[[section-technical-risks]]
== Risks and Technical Debts

Ésta es una lista de los riesgos que hemos tomado al empezar el proyecto:

- Utilizar tecnologías que ninguno de los integrantes del grupo conoce ni ha trabajado con ellas nunca en la vida.

- Tiempo de desarrollo corto. (Normalmente, utilizar tecnologías nuevas en lugar de utilizar alguna ya conocida se hace porque en un futuro será más mantenible el proyecto que si lo hicieramos con alguna otra tecnología más fácil, esa es la razón de tomar el riesgo. En este caso como el tiempo es limitado, es un riesgo muy alto utilizar una tecnología desconocida.)

- Uno de los riesgos más importantes es el hecho de trabajar con gente con la que no hemos trabajado nunca. Es un riesgo a tomar hacer un grupo con desconocidos, que puede salir bien, o mal.

- El riesgo de que pase el tiempo y no tengamos avanzado lo suficiente. Deberemos empezar a trabajar en el proyecto lo antes posible.

- Empezar a hacer la documentación antes que el código. Estar dos semanas desarrollando documentación sin haber tocado ni una línea de código del proyecto ni tener experiencia en solid ni en react.


En resumen, las únicas salvaguardas que podemos tomar para evitar los riesgos son las siguientes:

- Mantener el contacto con el grupo a través de llamadas por discord además de la hora semanal de clase.

- Empezar a desarrollar código funcional lo antes posible.

- Llevar al día el proyecto aprendiendo sobre react y solid y no dejarlo atrás.