version: '3'
services:
  solidserver:
    build:
            context: ./solid
            dockerfile: ./solid/Dockerfile
    ports:
    - "8443:8443"
  sampleweb:
    build: .
    ports:
    - "3000:3000"